apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:
  gce-pd-csi-driver
resources:
- ../../base/
patchesJson6902:
- path: max-grpc-log-length.yaml
  target:
    group: apps
    kind: Deployment
    name: csi-gce-pd-controller
    version: v1
- path: default-fstype.yaml
  target:
    group: apps
    kind: Deployment
    name: csi-gce-pd-controller
    version: v1
transformers:
- ../../images/stable-master
