grafana:
  additionalDataSources:
  - name: Loki
    type: loki
    url: http://loki.monitoring.svc.cluster.local:3100
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      httpMethod: GET
    secureJsonData: {}
