grafana:
  # Ensure default data sources are preserved  
  defaultDashboardsEnabled: true

  # Enable sidecar for automatic data source creation
  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: false # Disable auto default, we'll set it manually

  # Add all data sources explicitly to ensure they work
  additionalDataSources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://monitoring-kube-prometheus-prometheus:9090
    access: proxy
    isDefault: true # Only ONE default data source allowed
    editable: false
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
      httpMethod: POST

  - name: AlertManager
    type: alertmanager
    uid: alertmanager
    url: http://monitoring-kube-prometheus-alertmanager:9093
    access: proxy
    isDefault: false # NOT default
    editable: false
    jsonData:
      implementation: prometheus

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    isDefault: false # NOT default
    editable: true
    jsonData:
      maxLines: 1000
      httpMethod: GET
    secureJsonData: {}

# Ensure Prometheus components are properly configured
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

# Ensure AlertManager is enabled
alertmanager:
  enabled: true
