grafana:
  # Ensure default data sources are preserved
  defaultDashboardsEnabled: true
  # Add Loki as additional data source
  additionalDataSources:
  - name: Loki
    type: loki
    url: http://loki.monitoring.svc.cluster.local:3100
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      httpMethod: GET
    secureJsonData: {}

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000

# Ensure Prometheus components are properly configured
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

# Ensure AlertManager is enabled
alertmanager:
  enabled: true
