kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node
spec:
  template:
    spec:
      containers:
        - name: gce-pd-driver
          imagePullPolicy: Always
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node-win
spec:
  template:
    spec:
      containers:
        - name: gce-pd-driver
          imagePullPolicy: Always
