apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geth-node
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/onukwilip/oumla-devops-task.git'
    targetRevision: HEAD
    path: 'helm'  # Watch the entire helm directory
    helm:
      valueFiles:
      - 'values/goeth.yml'  # Relative to helm/ directory
      parameters:
      - name: image.tag
        value: stable

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
