apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: geth-vpa-recommend-only
  namespace: default
  labels:
    app: geth
    component: autoscaler
    type: vertical
    mode: recommendation-only
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: geth
  updatePolicy:
    updateMode: "Off" # Only provide recommendations, don't auto-update
  resourcePolicy:
    containerPolicies:
    - containerName: geth
      minAllowed:
        cpu: 100m
        memory: 500Mi
      maxAllowed:
        cpu: 4 # Higher limit for blockchain workloads
        memory: 8Gi # Higher memory limit for blockchain data
      controlledResources: [ "cpu", "memory" ]
      controlledValues: RequestsAndLimits
    - containerName: init-chown-data
      mode: "Off" # Don't autoscale init containers
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: geth-vpa-initial-only
  namespace: default
  labels:
    app: geth
    component: autoscaler
    type: vertical
    mode: initial-only
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: geth
  updatePolicy:
    updateMode: "Initial" # Only set resources on pod creation
  resourcePolicy:
    containerPolicies:
    - containerName: geth
      minAllowed:
        cpu: 100m
        memory: 500Mi
      maxAllowed:
        cpu: 4
        memory: 8Gi
      controlledResources: [ "cpu", "memory" ]
      controlledValues: RequestsAndLimits
    - containerName: init-chown-data
      mode: "Off"
