apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: geth-hpa-conservative
  namespace: default
  labels:
    app: geth
    component: autoscaler
    version: conservative
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: geth
  minReplicas: 1
  maxReplicas: 2 # Conservative scaling for blockchain nodes
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85 # Higher threshold for blockchain nodes
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90 # Higher threshold due to blockchain data requirements
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600 # 10 minutes - slow scale down
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300 # Only remove 1 pod every 5 minutes
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 300 # 5 minutes - moderate scale up
      policies:
      - type: Pods
        value: 1
        periodSeconds: 180 # Add 1 pod every 3 minutes max
      selectPolicy: Min
